# -*- coding: utf-8 -*-
"""ganttsipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GAN-qN7gkDPfZd5TkXl1iHa6z2k5H8fM
"""

!git clone https://github.com/yanggeng1995/GAN-TTS

cd GAN-TTS/

# Commented out IPython magic to ensure Python compatibility.
# %pwd

!python process.py --wav_dir="wavs" --output="data"

!pip install tensorboardx

!python train.py --input='data/train'

!python generate.py --input="data/test"

